from typing import List, Optional, Protocol

from vaybooks.bms.domain.boutique.measurements.entities import (
    MeasurementRecord,
    MeasurementSectionConfig,
    MeasurementSpecField,
)
from vaybooks.bms.domain.shared.enums import PersonType


class MeasurementSpecRepository(Protocol):
    def save(self, field: MeasurementSpecField) -> MeasurementSpecField: ...

    def find_by_id(self, field_id: str) -> Optional[MeasurementSpecField]: ...

    def find_by_key(
        self, key: str, person_type: Optional[PersonType] = None
    ) -> Optional[MeasurementSpecField]: ...

    def list_all(self, active_only: bool = False) -> List[MeasurementSpecField]: ...

    def list_for_person_type(
        self, person_type: PersonType, active_only: bool = True
    ) -> List[MeasurementSpecField]: ...

    def delete(self, field_id: str) -> None: ...


class MeasurementSectionRepository(Protocol):
    def save(self, section: MeasurementSectionConfig) -> MeasurementSectionConfig: ...

    def find_by_id(self, section_id: str) -> Optional[MeasurementSectionConfig]: ...

    def find_by_key(self, key: str) -> Optional[MeasurementSectionConfig]: ...

    def list_all(self, active_only: bool = False) -> List[MeasurementSectionConfig]: ...

    def delete(self, section_id: str) -> None: ...


class MeasurementRecordRepository(Protocol):
    def save(self, record: MeasurementRecord) -> MeasurementRecord: ...

    def find_by_id(self, record_id: str) -> Optional[MeasurementRecord]: ...

    def find_by_number(self, measurement_number: str) -> Optional[MeasurementRecord]: ...

    def list_by_customer(self, customer_id: str) -> List[MeasurementRecord]: ...

    def list_by_order(self, order_id: str) -> List[MeasurementRecord]: ...

    def list_all(self) -> List[MeasurementRecord]: ...

    def delete(self, record_id: str) -> None: ...
