from typing import List, Optional, Protocol

from vaybooks.bms.domain.parties.segments.entities import PartySegment


class PartySegmentRepository(Protocol):
    def save(self, segment: PartySegment) -> PartySegment: ...

    def find_by_id(self, segment_id: str) -> Optional[PartySegment]: ...

    def find_by_name(self, name: str) -> Optional[PartySegment]: ...

    def list_all(self, active_only: bool = False) -> List[PartySegment]: ...

    def delete(self, segment_id: str) -> None: ...
