from typing import List, Optional, Protocol

from vaybooks.bms.domain.purchases.entities import (
    GoodsReceipt,
    PurchaseOrder,
    PurchaseReturn,
)


class PurchaseOrderRepository(Protocol):
    def save(self, order: PurchaseOrder) -> PurchaseOrder: ...

    def find_by_id(self, order_id: str) -> Optional[PurchaseOrder]: ...

    def find_by_po_number(self, po_number: str) -> Optional[PurchaseOrder]: ...

    def list_all(self) -> List[PurchaseOrder]: ...

    def delete(self, order_id: str) -> None: ...


class GoodsReceiptRepository(Protocol):
    def save(self, grn: GoodsReceipt) -> GoodsReceipt: ...

    def find_by_id(self, grn_id: str) -> Optional[GoodsReceipt]: ...

    def find_by_grn_number(self, grn_number: str) -> Optional[GoodsReceipt]: ...

    def list_all(self) -> List[GoodsReceipt]: ...

    def list_by_po(self, purchase_order_id: str) -> List[GoodsReceipt]: ...

    def delete(self, grn_id: str) -> None: ...


class PurchaseReturnRepository(Protocol):
    def save(self, purchase_return: PurchaseReturn) -> PurchaseReturn: ...

    def find_by_id(self, return_id: str) -> Optional[PurchaseReturn]: ...

    def list_all(self) -> List[PurchaseReturn]: ...

    def delete(self, return_id: str) -> None: ...
