from typing import List, Optional, Protocol

from vaybooks.bms.domain.accounting.entities import Account, Voucher
from vaybooks.bms.domain.shared.enums import AccountType


class AccountRepository(Protocol):
    def save(self, account: Account) -> Account: ...

    def find_by_id(self, account_id: str) -> Optional[Account]: ...

    def find_by_name(self, name: str) -> Optional[Account]: ...

    def find_customer_account(self, customer_id: str) -> Optional[Account]: ...

    def find_vendor_account(self, vendor_id: str) -> Optional[Account]: ...

    def find_worker_account(self, worker_id: str) -> Optional[Account]: ...

    def list_all(self, active_only: bool = True) -> List[Account]: ...

    def customer_balances_by_customer(self) -> dict: ...

    def update_balance(self, account_id: str, debit: float, credit: float) -> None: ...


class VoucherRepository(Protocol):
    def save(self, voucher: Voucher) -> Voucher: ...

    def find_by_id(self, voucher_id: str) -> Optional[Voucher]: ...

    def delete(self, voucher_id: str) -> None: ...

    def find_by_invoice(self, invoice_id: str) -> Optional[Voucher]: ...

    def find_by_number(self, voucher_number: str) -> Optional[Voucher]: ...

    def list_by_account(self, account_id: str) -> List[Voucher]: ...

    def list_by_order(self, order_id: str) -> List[Voucher]: ...

    def list_all(self) -> List[Voucher]: ...


class CounterRepository(Protocol):
    def next(self, counter_name: str) -> str: ...

    def peek(self, counter_name: str) -> str: ...
