from typing import List, Optional, Protocol

from vaybooks.bms.domain.sales.entities import DeliveryNote, SalesOrder, SalesReturn


class SalesOrderRepository(Protocol):
    def save(self, order: SalesOrder) -> SalesOrder: ...

    def find_by_id(self, order_id: str) -> Optional[SalesOrder]: ...

    def find_by_so_number(self, so_number: str) -> Optional[SalesOrder]: ...

    def list_all(self) -> List[SalesOrder]: ...

    def delete(self, order_id: str) -> None: ...


class DeliveryNoteRepository(Protocol):
    def save(self, dn: DeliveryNote) -> DeliveryNote: ...

    def find_by_id(self, dn_id: str) -> Optional[DeliveryNote]: ...

    def find_by_dn_number(self, dn_number: str) -> Optional[DeliveryNote]: ...

    def list_all(self) -> List[DeliveryNote]: ...

    def list_by_so(self, sales_order_id: str) -> List[DeliveryNote]: ...

    def delete(self, dn_id: str) -> None: ...


class SalesReturnRepository(Protocol):
    def save(self, sales_return: SalesReturn) -> SalesReturn: ...

    def find_by_id(self, return_id: str) -> Optional[SalesReturn]: ...

    def list_all(self) -> List[SalesReturn]: ...

    def delete(self, return_id: str) -> None: ...
