from typing import List, Optional, Protocol

from vaybooks.bms.domain.parties.commission_agents.entities import CommissionAgent


class CommissionAgentRepository(Protocol):
    def save(self, agent: CommissionAgent) -> CommissionAgent: ...

    def find_by_id(self, agent_id: str) -> Optional[CommissionAgent]: ...

    def find_by_phone(self, phone: str) -> Optional[CommissionAgent]: ...

    def find_by_gstin(self, gstin: str) -> Optional[CommissionAgent]: ...

    def find_by_source_customer_id(
        self, customer_id: str
    ) -> Optional[CommissionAgent]: ...

    def search(self, query: str) -> List[CommissionAgent]: ...

    def list_all(self) -> List[CommissionAgent]: ...
