from typing import List, Optional, Protocol

from vaybooks.bms.domain.parties.customers.entities import Customer


class CustomerRepository(Protocol):
    def save(self, customer: Customer) -> Customer: ...

    def find_by_id(self, customer_id: str) -> Optional[Customer]: ...

    def find_by_phone(self, phone: str) -> Optional[Customer]: ...

    def find_by_gstin(self, gstin: str) -> Optional[Customer]: ...

    def search(
        self, query: str, location_filter: dict | None = None
    ) -> List[Customer]: ...

    def list_all(self, location_filter: dict | None = None) -> List[Customer]: ...
