from typing import List, Optional, Protocol

from vaybooks.bms.domain.parties.vendors.entities import Vendor


class VendorRepository(Protocol):
    def save(self, vendor: Vendor) -> Vendor: ...

    def find_by_id(self, vendor_id: str) -> Optional[Vendor]: ...

    def find_by_phone(self, phone: str) -> Optional[Vendor]: ...

    def find_by_gstin(self, gstin: str) -> Optional[Vendor]: ...

    def search(
        self, query: str, location_filter: dict | None = None
    ) -> List[Vendor]: ...

    def list_all(self, location_filter: dict | None = None) -> List[Vendor]: ...
