from typing import List, Optional, Protocol

from vaybooks.bms.domain.orders.entities import CustomizationOrder
from vaybooks.bms.domain.orders.value_objects import BillRegistryEntry


class OrderRepository(Protocol):
    def save(self, order: CustomizationOrder) -> CustomizationOrder: ...

    def find_by_id(self, order_id: str) -> Optional[CustomizationOrder]: ...

    def find_by_order_number(self, order_number: str) -> Optional[CustomizationOrder]: ...

    def find_by_order_activity_id(
        self, order_activity_id: str
    ) -> Optional[CustomizationOrder]: ...

    def search(self, query: str) -> List[CustomizationOrder]: ...

    def list_all(self) -> List[CustomizationOrder]: ...

    def list_by_status(self, status: str) -> List[CustomizationOrder]: ...

    def list_by_customer(self, customer_id: str) -> List[CustomizationOrder]: ...

    def list_recent_by_customer(
        self, customer_id: str, limit: int = 5
    ) -> List[CustomizationOrder]: ...

    def get_customer_summary(self, customer_id: str) -> dict: ...

    def update_order_activity(
        self, order_id: str, order_activity_id: str, updates: dict
    ) -> CustomizationOrder: ...


class BillRegistryRepository(Protocol):
    def register(self, entry: BillRegistryEntry) -> BillRegistryEntry: ...

    def find_by_bill_number(self, bill_number: str) -> Optional[BillRegistryEntry]: ...

    def exists(self, bill_number: str) -> bool: ...

    def unregister(self, bill_number: str) -> None: ...
