from typing import List, Optional, Protocol

from vaybooks.bms.domain.production.entities import (
    ProductionBatch,
    ProductionSettings,
    Recipe,
)
from vaybooks.bms.domain.shared.enums import ProductionBatchStatus


class RecipeRepository(Protocol):
    def save(self, recipe: Recipe) -> Recipe: ...
    def find_by_id(self, recipe_id: str) -> Optional[Recipe]: ...
    def find_by_code(self, code: str) -> Optional[Recipe]: ...
    def list_all(self, active_only: bool = True) -> List[Recipe]: ...
    def delete(self, recipe_id: str) -> None: ...


class ProductionBatchRepository(Protocol):
    def save(self, batch: ProductionBatch) -> ProductionBatch: ...
    def find_by_id(self, batch_id: str) -> Optional[ProductionBatch]: ...
    def find_by_number(self, batch_number: str) -> Optional[ProductionBatch]: ...
    def list_all(
        self, status: Optional[ProductionBatchStatus] = None
    ) -> List[ProductionBatch]: ...
    def delete(self, batch_id: str) -> None: ...


class ProductionSettingsRepository(Protocol):
    def get(self) -> ProductionSettings: ...
    def save(self, settings: ProductionSettings) -> ProductionSettings: ...
