from typing import List, Optional, Protocol

from vaybooks.bms.domain.inventory.entities import (
    InventoryProduct,
    ProductCategory,
    StockMovement,
)


class ProductCategoryRepository(Protocol):
    def save(self, category: ProductCategory) -> ProductCategory: ...

    def find_by_id(self, category_id: str) -> Optional[ProductCategory]: ...

    def find_by_name(self, name: str) -> Optional[ProductCategory]: ...

    def list_all(self, active_only: bool = True) -> List[ProductCategory]: ...

    def delete(self, category_id: str) -> None: ...


class InventoryProductRepository(Protocol):
    def save(self, product: InventoryProduct) -> InventoryProduct: ...

    def find_by_id(self, product_id: str) -> Optional[InventoryProduct]: ...

    def find_by_sku(self, sku: str) -> Optional[InventoryProduct]: ...

    def list_all(self, active_only: bool = True) -> List[InventoryProduct]: ...

    def list_by_category(self, category_id: str) -> List[InventoryProduct]: ...

    def count_by_category(self, category_id: str) -> int: ...

    def search(self, query: str) -> List[InventoryProduct]: ...


class StockMovementRepository(Protocol):
    def save(self, movement: StockMovement) -> StockMovement: ...

    def list_by_product(self, product_id: str) -> List[StockMovement]: ...

    def list_all(self) -> List[StockMovement]: ...
